### ISSUE TITLE
Window disappears when it loses focus

### ISSUE THREAD

**Issue by AloisMahdal** [rhysd/Mstdn#29] opened 2017-06-16 01:00 UTC
- Your OS: Fedora 25
- App version: Mstdn-linux-x64-0.2.5.zip

When i run ./Mstdn in i3 4.13-113-gd3901fe, the window disappears as soon as focus is lost.  The process still runs, just the window is lost so I have to kill the process manually.

This does not happen if I set `normal_window` to `true` or if I set NODE_ENV the way README suggests.

I haven't found any useful info printed to stdout/stderr or under ~/.local or similar place.

**Comment by rhysd** [comment] 2017-06-16 01:43
It's expected behavior. If `normal_window` is set to `false`, this app behave as 'menubar window' mode. Menu items are hidden when losing its focus (e.g. click WiFi icon in menu bar). 'menubar window' mode follows this behavior.

**Comment by rhysd** [comment] 2017-06-16 01:44
If you want to set window visible always, please set `always_on_top` to `true`.

**Comment by AloisMahdal** [comment] 2017-06-16 02:12
Well, a bit strange for a default setting.  I guess in this mode I can only access Mstdn by clicking the tray icon (which I did not notice until after your explanation).

`always_on_top` works fine, though.

**Comment by rhysd** [comment] 2017-06-20 08:40
I'll close this because `always_on_top` works and I added more description to README

**Closed as completed by rhysd** 2017-06-20 08:40 UTC
